# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/woof/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# This should do for```
# $ stack setup
# $ stack install xmonad taffybar status-notifier-item
# ```
# Make sure to install libxinerama-dev, gobject-introspection, libdbusmenu-gtk3,
# libxss-dev
# TODO: figure out how to use stack properly and add a real project config file
# https://github.com/commercialhaskell/stack/issues/710
# https://github.com/taffybar/taffybar/issues/140
#
# hledger instructions use:
# stack install --resolver=lts hledger-lib-1.16.1 hledger-1.16.1 hledger-ui-1.16.1 hledger-web-1.16.1
# which is probably saner and I should use for xmonad too...
packages: []
resolver: lts-22.27
extra-deps:
  - taffybar-4.0.2
  - xmonad-contrib-0.18.0
# https://github.com/haskell-gi/haskell-gi/issues/318
  - gi-atk-2.0.28
  - gi-cairo-1.0.30
  - gi-cairo-connector-0.1.1
  - gi-cairo-render-0.1.2
  - gi-dbusmenu-0.4.14
  - gi-dbusmenugtk3-0.4.15
  - gi-gdk-3.0.29
  - gi-gdkpixbuf-2.0.32
  - gi-gdkx11-3.0.16
  - gi-gio-2.0.34
  - gi-glib-2.0.30
  - gi-gobject-2.0.31
  - gi-gtk-3.0.43
  - gi-gtk-hs-0.3.16
  - gi-harfbuzz-0.0.10
  - gi-pango-1.0.30
  - gi-xlib-2.0.14
  - gtk-sni-tray-0.1.8.1
  - haskell-gi-0.26.10
  - haskell-gi-base-0.26.6
  - xdg-desktop-entry-0.1.1.2
