# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/woof/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# This should do for a `stack setup ; stack install xmonad taffybar status-notifier-item`
# Make sure to install libxinerama-dev, gobject-introspection, libdbusmenu-gtk3, libxss-dev
# TODO: figure out how to use stack properly and add a real project config file
# https://github.com/commercialhaskell/stack/issues/710
# https://github.com/taffybar/taffybar/issues/140
#
packages: []
resolver: lts-12.18
extra-deps:
  - xmonad-0.15
  - xmonad-contrib-0.15
  - taffybar-3.0.0
  - split-0.2.3.3
  # Transitive:
  - ConfigFile-1.1.4
  - dbus-1.0.1
  - dbus-hslogger-0.1.0.1
  - gi-dbusmenu-0.4.1
  - gi-dbusmenugtk3-0.4.2
  - gi-gdk-3.0.16
  - gi-gdkpixbuf-2.0.16
  - gi-gdkx11-3.0.2
  - gi-gio-2.0.18
  - gi-gtk-3.0.25
  - gi-gtk-hs-0.3.6.3
  - gi-pango-1.0.16
  - gi-xlib-2.0.2
  - gio-0.13.5.0
  - gtk-sni-tray-0.1.5.0
  - gtk-strut-0.1.2.1
  - gtk-traymanager-1.0.1
  - gtk3-0.14.9
  - rate-limit-1.4.1
  - spool-0.1
  - status-notifier-item-0.3.0.0
  - time-units-1.0.0
  - xml-helpers-1.0.0

